name: Test

on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
